apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHN2Ynhsd2Fo
  CLOUDINARY_KEY: ODU5NDg5MTQ2MjM1MzIx
  CLOUDINARY_SECRET: MDdZZkRYSEU1akFrNHd4LXNjdkI3MThtd1Q4
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZV1JwYW1GcGMzZGhiQ0lzSW1FaU9pSmpiSFl3TnpKemVHNHhaRzR5TW1wd1ltWm1OSFZ3YlhObUluMC5SVlFZc3UwUnZKZ0NGNTRrMjJkWDBB
  DB_URL: bW9uZ29kYitzcnY6Ly9rYWJlZXI6OWxQaFgwWlJ1MURUUXZXVEBkZXYta2FiZWVyLmpsZ3k2c3AubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPWRldi1rYWJlZXI=
  SECRET: ZGV2a2FiZWVy